# Array

In [6]:
import numpy as np

x =[1,2,3,4]

y = np.array([1,2,3,4,5])

print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
l = []

for i in range(1,5):
    int_1 = int(input("enter :"))
    l.append(int_1)
    
print(np.array(l))

enter :12
enter :13
enter :14
enter :15
['12' '13' '14' '15']


In [7]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [11]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [13]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
