# Random

# Rand() function

In [1]:
import numpy as np

var = np.random.rand(4)

print(var)

[0.8031624  0.94938533 0.18070943 0.31261265]


In [3]:
var1 = np.random.rand(2,5)

print(var1)

[[0.3673799  0.19118712 0.10687928 0.49048125 0.49731488]
 [0.71357632 0.68292861 0.76259456 0.42877525 0.85006351]]


# randn()

In [4]:
var2 = np.random.randn(5)

print(var2)


[ 0.84142182  0.44071144  0.26118688  2.66366132 -0.35147884]


# randf()

In [6]:
var3 = np.random.ranf(4)

print(var3)

[0.69646536 0.50505722 0.00890569 0.40205267]


# randit()

In [12]:
var4 = np.random.randint(5,20,5)

print(var4)

[10  8 12 14  9]
