# Data Type

In [2]:
import numpy as np

var = np.array([1,2,3,4])\

print("Data Type : ",var.dtype)

Data Type :  int32


In [3]:
var = np.array([1.0,1.2,1.3])

print("Data Type : ",var.dtype)

Data Type :  float64


In [5]:
var = np.array(["a","s","d","f"])

print("data type :", var.dtype)

data type : <U1


In [6]:
var = np.array(["a","s","d","f",1,2,3,4])

print("data type : ",var.dtype)

data type :  <U11


In [9]:
x = np.array([1,2,3,4],dtype = np.int8)

print("data type :", x.dtype)
print(x)

data type : int8
[1 2 3 4]


In [11]:
x1 = np.array([1,2,3,4],dtype = "f")

print("data type : ",x1.dtype)
print(x1)

data type :  float32
[1. 2. 3. 4.]


In [15]:
x2 = np.array([1,2,3,4])

new = np.float32(x2)

new_one = np.int_(new)

print("data type : ",x2.dtype)
print("data type : ",new.dtype)
print("data type : ",new_one.dtype)

print(x2)
print(new)
print(new_one)

data type :  int32
data type :  float32
data type :  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [17]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
