# Insert

In [6]:
import numpy as np

var = np.array([1,2,3,4])

print(var)

v =np.insert(var , (2,4) , 6.5)

print(v)

[1 2 3 4]
[1 2 6 3 4 6]


In [11]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1, 2,[22,13,34] ,axis = 0)

print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [22 13 34]]


# Delete

In [12]:
var3 = np.array([1,2,3,4])

print(var3)

d = np.delete(var3,2)
print(d)


[1 2 3 4]
[1 2 4]
