# Indexing 

In [2]:
import numpy as np

var = np.array([9,8,7,6])
#               0,1,2,3
#             -4,-3,-2,-1

print(var[1])
print(var[-3])

8
8


In [5]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,1])

[[9 8 7]
 [4 5 6]]
2

8


In [8]:
var2 = np.array([[[1,2,],[6,7]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1])

[[[1 2]
  [6 7]]]
3

[6 7]
