# Matrix

In [7]:
import numpy as np

var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var)
print(type(var))
print()
print(var*var2)
print()
print(var.dot(var2))


[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [3]:
var1 = np.array([[1,2,3],[1,2,3]])

print(var1)
print(type(var1))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

var2 = np.matrix([[1,2,3],[4,5,6]])

print(var2)
print()

print(np.transpose(var2))
print(var2.T)
print()
print(np.swapaxes(var2,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [7]:
var3 = np.matrix([[1,2],[3,4]])
print(var3)
print()
print(np.swapaxes(var3,0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [8]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()

print(np.linalg.inv(var4))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
var5 = np.matrix([[1,2],[3,4]])
print(var5)
print()

print(np.linalg.matrix_power(var5,2))
print()

print(np.linalg.matrix_power(var5,0))
print()

print(np.linalg.matrix_power(var5,-2))
print()


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [17]:
var6 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var6)
print()
print(np.linalg.det(var6))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
