# Aerithmetic Operation

In [1]:
import numpy as np

var = np.array([1,2,3,4])

varadd = var + 3

print(varadd)

[4 5 6 7]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2

print(varadd)

[2 4 6 8]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)

print(varadd)

[2 4 6 8]


In [3]:
var = np.array([1,2,3,4])

varadd = var * 3

print(varadd)

[ 3  6  9 12]


In [4]:
var = np.array([1,2,3,4])

varadd = var / 3

print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [5]:
var = np.array([1,2,3,4])

varadd = var % 3

print(varadd)

[1 2 0 1]


In [6]:
 var = np.array([1,2,3,4])

varadd = var - 3

print(varadd)

[-2 -1  0  1]


In [13]:
var = np.array([1,2,3,4])

varadd = np.reciprocal(var)

print(varadd)

[1 0 0 0]


# 2D array

In [11]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2 = var21 + var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [14]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()

varadd2 = var21 * var22

print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]
