In [2]:
import numpy as np

var = np.array([1,2,3,4,5])

np.random.shuffle(var)

print(var)

[5 3 1 4 2]


In [5]:
var1 = np.array([1,2,3,4,2,5,2,6,7])

x = np.unique(var1,return_index = True,return_counts=True)

print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


In [6]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(2,3))

print(y)

[[1 2 3]
 [4 5 6]]


In [9]:
 var3 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print(y)

print("Flattern : ",y.flatten(order = "F"))
print("Ravel :",np.ravel(y,order = "A"))

[[1 2]
 [3 4]
 [5 6]]
Flattern :  [1 3 5 2 4 6]
Ravel : [1 2 3 4 5 6]
