
# Serch

In [1]:
import numpy as np

var = np.array([1,2,3,4,2,5,2,5,6,7])

x = np.where( var == 2)

print(x)

(array([1, 4, 6], dtype=int64),)


In [4]:
var1 = np.array([1,2,3,4,2,5,2,5,6,7])

x1 = np.where( (var%2) == 0)

print(x1)

(array([1, 3, 4, 6, 8], dtype=int64),)


In [13]:
var2 = np.array([1,2,3,4,6,7,8])

x2 = np.searchsorted( var1 , 4 ,side="right")

print(x2)

5


# sort

In [16]:
var_2 = np.array([[4,2,3],[1,12,5],[22,52,6]])


print(np.sort(var_2))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [15]:
var_3 = np.array(["a","s","d","f"])


print(np.sort(var_3))

['a' 'd' 'f' 's']


# Filter Array

In [18]:
var_4 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_4[f]

print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>
