In [1]:
import sklearn
import pandas as pd
import numpy as np

In [2]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [3]:
y

array([0, 1, 1, 1])

In [4]:
w = np.array([1,1])
w

array([1, 1])

In [5]:
b = -0.5

In [13]:
pred = []
for a in x:
    y_hat = np.dot(a,w)+b
    pred.append(activation(y_hat)) # 2 pachhi karva no like that niche 1 valo thai jay pachhi aa karva no

In [14]:
pred # and last ma aa karva no  

[0, 1, 1, 1]

In [12]:
def activation(z):
    if z >= 0:
        return 1
    else:
        return 0  # first output aane karva no

In [16]:
import math
import numpy as np

In [17]:
epochs = 100
alpha = 0.2

In [18]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print("initial weights:")
print("w0 = ",w0, "w1 = 1",w1, "w2 = ",w2 )

initial weights:
w0 =  0.3844431669349523 w1 = 1 0.5030581960103596 w2 =  0.619602937069424


In [19]:
del_w0 = 1
del_w2 = 1
del_w1 = 1

In [20]:
train_data_temp = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1,]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [21]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [22]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [24]:
bias = 0
for i in range(epochs):
    j = 0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias
        
        if (y_hat >= 0):
            act =1 
        else:
            act = 0
            
        err = op[j] -act
        
        del_w0 = alpha*x[0]*err
        del_w1 = alpha*x[1]*err
        del_w2 = alpha*x[2]*err
        
        w0 = w0+ del_w0
        w1 = w1+ del_w1
        w2 = w2+ del_w2
        
        j =j+1
        print("epoch", i+1, "error =",err)
        print(del_w0,del_w1,del_w2)
        
print("\nFinal weights =")
print("w0 =",w0, "w1 =",w1, "w2 =",w2)

epoch 1 error = -1
-0.0 -0.0 -0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 1 error = 0
0.0 0.0 0.0
epoch 2 error = -1
-0.0 -0.0 -0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 2 error = 0
0.0 0.0 0.0
epoch 3 error = -1
-0.0 -0.0 -0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 3 error = 0
0.0 0.0 0.0
epoch 4 error = -1
-0.0 -0.0 -0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 4 error = 0
0.0 0.0 0.0
epoch 5 error = -1
-0.0 